apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cascpm
  namespace: mc-b
  description: CAS CPM
  tags:
    - container
    - kubernetes
    - education
    - hslu
  links:
  - url: https://github.com/mc-b/cascpm
    title: Repository
    icon: github
  annotations:
    github.com/project-slug: mc-b/cascpm
    backstage.io/source-location: url:https://github.com/mc-b/cascpm
    # backstage.io/techdocs-ref: url:https://github.com/mc-b/cascpm
spec:
  type: website
  lifecycle: production
  owner: group:mc-b/mc-b
