apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cascpm
  annotations:
    github.com/project-slug: mc-b/cascpm
spec:
  type: service
  lifecycle: production
  owner: education
