apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: Ein cooler Demo-Service in Backstage
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/mc-b/cascpm/blob/v2.0.0/README.md
spec:
  type: service
  lifecycle: production
  owner: demo-team
