apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: autoshop-gmbh
  description: The autoshop-gmbh organization
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Auto Shop GmbH
    email: info@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  children: [app,education,infra]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: autoshop-groups
  description: Alle Gruppen
spec:
  targets:
    - ./app/app-department.yaml
    - ./app/backoffice-team.yaml
    - ./app/backoffice-domain.yaml       
    - ./app/garage-team.yaml
    - ./app/iot-team.yaml
    - ./app/maintenance-team.yaml
    - ./app/management-team.yaml
    - ./app/management-domain.yaml    
    - ./app/shop-team.yaml   
    - ./app/shop-domain.yaml    
    - ./education/education-department.yaml
    - ./infra/infra-department.yaml
    - ./infra/team-iiot-group.yaml 

