apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: app
  description: Applikationsentwicklung
spec:
  type: department
  profile:
    displayName: Abteilung Applikationsentwicklung  
  parent: autoshop-gmbh
  children: []
