apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: management-system
  title: Management System
  description: Internal tools and services used for business management, such as sales and reporting.
spec:
  owner: management-team

---
# sales
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: management-sales
  description: Sales analytics and reporting service.
spec:
  type: service
  lifecycle: production
  owner: management-team
  system: management-system
  dependsOn:
    - component:default/shop-webshop  

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: management-sales-api
spec:
  type: openapi
  lifecycle: production
  owner: management-team
  system: management-system
  definition: ./openapi/sales.yaml
  providesApis:
    - management-sales-api
