apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: iot
  description: IoT Team der Auto Shop GmbH
spec:
  type: team
  parent: app
  children: []
  members:
    - alex.meier
    - nina.hoffmann

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alex.meier
spec:
  profile:
    displayName: Alex Meier
    email: alex.meier@autoshopgmbh.de
  memberOf: [iot]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nina.hoffmann
spec:
  profile:
    displayName: Nina Hoffmann
    email: nina.hoffmann@autoshopgmbh.de
  memberOf: [iot]
