apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: maintenance
  description: Wartungsteam der Auto Shop GmbH
spec:
  type: team
  parent: app
  children: []
  members:
    - paul.fischer
    - emily.schneider

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: paul.fischer
spec:
  profile:
    displayName: Paul Fischer
    email: paul.fischer@autoshopgmbh.de
  memberOf: [maintenance]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: emily.schneider
spec:
  profile:
    displayName: Emily Schneider
    email: emily.schneider@autoshopgmbh.de
  memberOf: [maintenance]
