apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: shop
  description: Verkaufsteam der Auto Shop GmbH
spec:
  type: team
  parent: app
  children: []
  members:
    - anna.lehmann
    - david.kraus

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: anna.lehmann
spec:
  profile:
    displayName: Anna Lehmann
    email: anna.lehmann@autoshopgmbh.de
  memberOf: [shop]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: david.kraus
spec:
  profile:
    displayName: David Kraus
    email: david.kraus@autoshopgmbh.de
  memberOf: [shop]
